-- Jezyk SQL. Rozdzial 5b.
-- Polaczenia zaawansowane -- zadania

-- Exercise 1
SELECT
    P.NAZWISKO,
    P.ID_ZESP,
    Z.NAZWA
FROM PRACOWNICY P LEFT JOIN ZESPOLY Z
                            ON P.ID_ZESP = Z.ID_ZESP
ORDER BY P.NAZWISKO;

/*
NAZWISKO ID_ZESP NAZWA
--------------- ------- ------------------
BIALY 30 SYSTEMY EKSPERCKIE
BLAZEWICZ 40 ALGORYTMY
BRZEZINSKI 20 SYSTEMY ROZPROSZONE
HAPKE 30 SYSTEMY EKSPERCKIE
JEZIERSKI 20 SYSTEMY ROZPROSZONE
KONOPKA 20 SYSTEMY ROZPROSZONE
KOSZLAJDA 20 SYSTEMY ROZPROSZONE
KROLIKOWSKI 20 SYSTEMY ROZPROSZONE
MAREK 10 ADMINISTRACJA
MATYSIAK 20 SYSTEMY ROZPROSZONE
MORZY 20 SYSTEMY ROZPROSZONE
SLOWINSKI 30 SYSTEMY EKSPERCKIE
WEGLARZ 10 ADMINISTRACJA
WOLNY
ZAKRZEWICZ 30 SYSTEMY EKSPERCKIE
*/

-- Exercise 2
SELECT
    Z.NAZWA,
    P.ID_ZESP,
    CASE
        WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO
        WHEN P.NAZWISKO IS NULL THEN 'brak pracownikow'
        END AS PRACOWNIK
FROM PRACOWNICY P RIGHT JOIN ZESPOLY Z
                             ON P.ID_ZESP = Z.ID_ZESP
ORDER BY Z.NAZWA, P.NAZWISKO;

/*
NAZWA ID_ZESP PRACOWNIK
----------------------- ------- ------------------
ADMINISTRACJA 10 MAREK
ADMINISTRACJA 10 WEGLARZ
ALGORYTMY 40 BLAZEWICZ
BADANIA OPERACYJNE 50 brak pracownikow
SYSTEMY EKSPERCKIE 30 BIALY
SYSTEMY EKSPERCKIE 30 HAPKE
SYSTEMY EKSPERCKIE 30 SLOWINSKI
SYSTEMY EKSPERCKIE 30 ZAKRZEWICZ
SYSTEMY ROZPROSZONE 20 BRZEZINSKI
SYSTEMY ROZPROSZONE 20 JEZIERSKI
SYSTEMY ROZPROSZONE 20 KONOPKA
SYSTEMY ROZPROSZONE 20 KOSZLAJDA
SYSTEMY ROZPROSZONE 20 KROLIKOWSKI
SYSTEMY ROZPROSZONE 20 MATYSIAK
SYSTEMY ROZPROSZONE 20 MORZY
*/

-- Exercise 3
SELECT
    Z.NAZWA AS ZESPOL,
    CASE
        WHEN P.NAZWISKO IS NOT NULL THEN P.NAZWISKO
        WHEN P.NAZWISKO IS NULL THEN 'brak pracownikow'
        END AS PRACOWNIK
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z
                                   ON P.ID_ZESP = Z.ID_ZESP
ORDER BY Z.NAZWA, P.NAZWISKO;

/*
ZESPOL PRACOWNIK
--------------------- -----------------
ADMINISTRACJA MAREK
ADMINISTRACJA WEGLARZ
ALGORYTMY BLAZEWICZ
BADANIA OPERACYJNE brak pracownikÃ³w
SYSTEMY EKSPERCKIE BIALY
SYSTEMY EKSPERCKIE HAPKE
SYSTEMY EKSPERCKIE SLOWINSKI
SYSTEMY EKSPERCKIE ZAKRZEWICZ
SYSTEMY ROZPROSZONE BRZEZINSKI
SYSTEMY ROZPROSZONE JEZIERSKI
SYSTEMY ROZPROSZONE KONOPKA
SYSTEMY ROZPROSZONE KOSZLAJDA
SYSTEMY ROZPROSZONE KROLIKOWSKI
SYSTEMY ROZPROSZONE MATYSIAK
SYSTEMY ROZPROSZONE MORZY
brak zespolu WOLNY
*/

-- Exercise 4
SELECT
    Z.NAZWA AS ZESPOL,
    COUNT(P.ID_ZESP) AS LICZBA,
    SUM(P.PLACA_POD) AS SUMA_PLAC
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z
                                   ON P.ID_ZESP = Z.ID_ZESP
GROUP BY Z.NAZWA
ORDER BY Z.NAZWA;

/*
ZESPOL LICZBA SUMA_PLAC
----------------------- ------ -----------
ADMINISTRACJA 2 2140,2
ALGORYTMY 1 1350
BADANIA OPERACYJNE 0
SYSTEMY EKSPERCKIE 4 2008
SYSTEMY ROZPROSZONE 7 4316,2
*/

-- Exercise 5
SELECT
    Z.NAZWA AS NAZWA
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z
                                   ON P.ID_ZESP = Z.ID_ZESP
GROUP BY Z.NAZWA
HAVING (COUNT(P.ID_ZESP) <= 0)
ORDER BY Z.NAZWA;

/*
NAZWA
------------------
BADANIA OPERACYJNE
*/

-- Exercise 6
SELECT
    P.NAZWISKO,
    P.ID_PRAC,
    S.NAZWISKO AS SZEF,
    P.ID_SZEFA
FROM PRACOWNICY P LEFT OUTER JOIN PRACOWNICY S
                                  ON P.ID_SZEFA = S.ID_PRAC
ORDER BY NAZWISKO;

/*
PRACOWNIK ID_PRAC SZEF ID_SZEFA
--------------- ------- -------------- --------
BIALY 210 BRZEZINSKI 130
BLAZEWICZ 110 WEGLARZ 100
BRZEZINSKI 130 WEGLARZ 100
HAPKE 230 SLOWINSKI 120
JEZIERSKI 170 BRZEZINSKI 130
KONOPKA 220 BLAZEWICZ 110
KOSZLAJDA 160 BRZEZINSKI 130
KROLIKOWSKI 150 BRZEZINSKI 130
MAREK 180 WEGLARZ 100
MATYSIAK 190 MORZY 140
MORZY 140 BRZEZINSKI 130
SLOWINSKI 120 WEGLARZ 100
WEGLARZ 100
ZAKRZEWICZ 200 MORZY 140
*/

-- Exercise 7
SELECT
    S.NAZWISKO AS PRACOWNIK,
    COUNT(*) AS PODWLADNY
FROM PRACOWNICY P
         INNER JOIN PRACOWNICY S
                    ON P.ID_SZEFA = S.ID_PRAC
GROUP BY S.NAZWISKO
ORDER BY S.NAZWISKO;

/*PRACOWNIK LICZBA_PODWLADNYCH
--------------- ------------------
BIALY 0
BLAZEWICZ 1
BRZEZINSKI 5
HAPKE 0
JEZIERSKI 0
KONOPKA 0
KOSZLAJDA 0
KROLIKOWSKI 0
MAREK 0
MATYSIAK 0
MORZY 2
SLOWINSKI 1
WEGLARZ 4
ZAKRZEWICZ 0
*/

-- Exercise 8
SELECT
    P.NAZWISKO,
    P.ETAT,
    P.PLACA_POD,
    Z.NAZWA,
    S.NAZWISKO AS SZEF
FROM PRACOWNICY P
         LEFT JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
         LEFT JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP
ORDER BY P.NAZWISKO;

/*
NAZWISKO ETAT PLACA_POD NAZWA SZEF
------------- -------------- --------- --------------------- -------------
BIALY STAZYSTA 250 SYSTEMY EKSPERCKIE BRZEZINSKI
BLAZEWICZ PROFESOR 1350 ALGORYTMY WEGLARZ
BRZEZINSKI PROFESOR 960 SYSTEMY ROZPROSZONE WEGLARZ
HAPKE ASYSTENT 480 SYSTEMY EKSPERCKIE SLOWINSKI
JEZIERSKI ASYSTENT 439,7 SYSTEMY ROZPROSZONE BRZEZINSKI
KONOPKA ASYSTENT 480 SYSTEMY ROZPROSZONE BLAZEWICZ
KOSZLAJDA ADIUNKT 590 SYSTEMY ROZPROSZONE BRZEZINSKI
KROLIKOWSKI ADIUNKT 645,5 SYSTEMY ROZPROSZONE BRZEZINSKI
MAREK SEKRETARKA 410,2 ADMINISTRACJA WEGLARZ
MATYSIAK ASYSTENT 371 SYSTEMY ROZPROSZONE MORZY
MORZY PROFESOR 830 SYSTEMY ROZPROSZONE BRZEZINSKI
SLOWINSKI PROFESOR 1070 SYSTEMY EKSPERCKIE WEGLARZ
WEGLARZ DYREKTOR 1730 ADMINISTRACJA
ZAKRZEWICZ STAZYSTA 208 SYSTEMY EKSPERCKIE MORZY
*/

-- Exercise 9
SELECT
    P.NAZWISKO,
    Z.NAZWA
FROM PRACOWNICY P, ZESPOLY Z
ORDER BY P.NAZWISKO, Z.NAZWA;

/*
NAZWISKO NAZWA
------------ ------------------
BIALY ADMINISTRACJA
BIALY ALGORYTMY
BIALY BADANIA OPERACYJNE
BIALY SYSTEMY EKSPERCKIE
BIALY SYSTEMY ROZPROSZONE
BLAZEWICZ ADMINISTRACJA
BLAZEWICZ ALGORYTMY
...
WEGLARZ SYSTEMY EKSPERCKIE
WEGLARZ SYSTEMY ROZPROSZONE
ZAKRZEWICZ ADMINISTRACJA
ZAKRZEWICZ ALGORYTMY
ZAKRZEWICZ BADANIA OPERACYJNE
ZAKRZEWICZ SYSTEMY EKSPERCKIE
ZAKRZEWICZ SYSTEMY ROZPROSZONE
*/

-- Exercise 10
SELECT
    COUNT(*)
FROM PRACOWNICY P, ZESPOLY Z, ETATY E;

/*
COUNT(*)
----------
420
*/

-- Exercise 11
SELECT DISTINCT
    E.NAZWA AS ETAT
FROM PRACOWNICY P LEFT JOIN ETATY E
                            ON P.ETAT = E.NAZWA
WHERE EXTRACT(YEAR FROM P.ZATRUDNIONY) = '1992'
   OR EXTRACT(YEAR FROM P.ZATRUDNIONY) = '1993'
ORDER BY E.NAZWA;

/*
ETAT
----------
ASYSTENT
(CZY TU NIE BRAKUJE STAZYSTA?
W MOJEJ BAZIE DANYCH: BIALY ZATRUDNIONY 10/14/1993, 11:00:00 PM JEST STAZYSTA (?)
*/

-- Exercise 12
SELECT
    Z.ID_ZESP
FROM PRACOWNICY P
         RIGHT JOIN ZESPOLY Z
                    ON P.ID_ZESP = Z.ID_ZESP
WHERE Z.ID_ZESP NOT IN (SELECT ID_ZESP FROM PRACOWNICY);

/*
ID_ZESP
---------
50
*/

-- Exercise 13
SELECT
    Z.ID_ZESP,
    Z.NAZWA
FROM PRACOWNICY P
         RIGHT JOIN ZESPOLY Z
                    ON P.ID_ZESP = Z.ID_ZESP
WHERE Z.ID_ZESP NOT IN (SELECT ID_ZESP FROM PRACOWNICY);

/*
ID_ZESP NAZWA
--------- ------------------
50 BADANIA OPERACYJNE
*/

-- Exercise 14
SELECT NAZWISKO, PLACA_POD,
       'Ponizej 480 zlotych' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD < 480
UNION
SELECT NAZWISKO, PLACA_POD,
       'Dokladnie 480 zlotych' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD = 480
UNION
SELECT NAZWISKO, PLACA_POD,
       'Powyzej 480 zlotych' AS PROG
FROM PRACOWNICY
WHERE PLACA_POD > 480
ORDER BY PLACA_POD;


/*
NAZWISKO PLACA_POD PROG
--------------- --------- ---------------------
ZAKRZEWICZ 208 Poni?ej 480 z?otych
BIALY 250 Poni?ej 480 z?otych
MATYSIAK 371 Poni?ej 480 z?otych
MAREK 410,2 Poni?ej 480 z?otych
JEZIERSKI 439,7 Poni?ej 480 z?otych
HAPKE 480 Dokladnie 480 z?otych
KONOPKA 480 Dokladnie 480 z?otych
KOSZLAJDA 590 Powy?ej 480 z?otych
KROLIKOWSKI 645,5 Powy?ej 480 z?otych
MORZY 830 Powy?ej 480 z?otych
BRZEZINSKI 960 Powy?ej 480 z?otych
SLOWINSKI 1070 Powy?ej 480 z?otych
BLAZEWICZ 1350 Powy?ej 480 z?otych
WEGLARZ 1730 Powy?ej 480 z?otych
*/
