-- Jezyk SQL. Rozdzial 6b
-- Podzapytania - konstrukcje zaawansowane

-- Exercise 1
SELECT *
FROM ZESPOLY Z
WHERE ID_ZESP NOT IN
      (SELECT ID_ZESP FROM PRACOWNICY
       GROUP BY ID_ZESP
       HAVING ID_ZESP = Z.ID_ZESP);

/*
ID_ZESP NAZWA ADRES
--------- -------------------- --------------------
50 BADANIA OPERACYJNE MIELZYNSKIEGO 30
*/

-- Exercise 2
SELECT
    NAZWISKO,
    PLACA_POD,
    P.ETAT
FROM PRACOWNICY P
WHERE PLACA_POD >
      (SELECT AVG(PLACA_POD)
       FROM PRACOWNICY WHERE ETAT = P.ETAT)
ORDER BY PLACA_POD DESC;

/*
NAZWISKO PLACA_POD ETAT
--------------- --------- --------
BLAZEWICZ 1350 PROFESOR
SLOWINSKI 1070 PROFESOR
KROLIKOWSKI 645,5 ADIUNKT
KONOPKA 480 ASYSTENT
HAPKE 480 ASYSTENT
BIALY 250 STAZYSTA
*/

-- Exercise 3
SELECT
    NAZWISKO,
    PLACA_POD
FROM PRACOWNICY P
WHERE PLACA_POD >
      (SELECT (S.PLACA_POD*0.75)
       FROM PRACOWNICY P1
                INNER JOIN PRACOWNICY S
                           ON P1.ID_SZEFA = S.ID_PRAC
       WHERE P1.ID_PRAC = P.ID_PRAC)
ORDER BY NAZWISKO;

SELECT
    NAZWISKO,
    PLACA_POD
FROM PRACOWNICY P
WHERE PLACA_POD > 0.75 * (SELECT PLACA_POD FROM PRACOWNICY
                          WHERE P.ID_SZEFA = ID_PRAC);

SELECT
    P.NAZWISKO,
    P.PLACA_POD
FROM PRACOWNICY P JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
WHERE P.PLACA_POD > 0.75* S.PLACA_POD;

/*
NAZWISKO PLACA_POD
--------------- ----------
BLAZEWICZ 1350
MORZY 830
*/

-- Exercise 4
SELECT
    NAZWISKO
FROM PRACOWNICY P
WHERE ETAT = 'PROFESOR'
  AND NOT EXISTS (SELECT S.NAZWISKO, Pu.ETAT
                  FROM PRACOWNICY Pu
                           INNER JOIN PRACOWNICY S
                                      ON Pu.ID_SZEFA = S.ID_PRAC
                  WHERE Pu.ETAT = 'STAZYSTA'
                    AND S.NAZWISKO = P.NAZWISKO);

/*
NAZWISKO
---------------
BLAZEWICZ
SLOWINSKI
*/

-- Exercise 5
SELECT
    Z.NAZWA,
    M.MAKS_SUMA_PLAC
FROM
    (SELECT MAX(SUMA_PLAC) AS MAKS_SUMA_PLAC FROM
        (SELECT SUM(PLACA_POD) AS SUMA_PLAC
         FROM PRACOWNICY GROUP BY ID_ZESP)) M,
    (SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC
     FROM PRACOWNICY GROUP BY ID_ZESP) S,
    ZESPOLY Z
WHERE
        S.ID_ZESP = Z.ID_ZESP
  AND
        S.SUMA_PLAC = M.MAKS_SUMA_PLAC;

/*
NAZWA MAKS_SUMA_PLAC
----------------------- --------------
SYSTEMY ROZPROSZONE 4316,2
*/

-- Exercise 6
SELECT
    NAZWISKO,
    PLACA_POD
FROM PRACOWNICY P
WHERE PLACA_POD NOT IN
      (SELECT PLACA_POD FROM PRACOWNICY
       WHERE PLACA_POD = p.PLACA_POD
         AND PLACA_POD < (SELECT MAX(PLACA_POD) FROM PRACOWNICY
                          WHERE PLACA_POD < (SELECT MAX(PLACA_POD) FROM PRACOWNICY
                                             WHERE PLACA_POD < (SELECT MAX(PLACA_POD) FROM PRACOWNICY))))
ORDER BY PLACA_POD DESC;

/*
NAZWISKO PLACA_POD
--------------- ----------
WEGLARZ 1730
BLAZEWICZ 1350
SLOWINSKI 1070
*/

-- Exercise 7
SELECT (EXTRACT(YEAR FROM ZATRUDNIONY)) AS ROK, COUNT(*) AS LICZBA FROM PRACOWNICY
GROUP BY (EXTRACT(YEAR FROM ZATRUDNIONY))
ORDER BY COUNT(*) DESC;

/*
ROK LICZBA
---- ---------
1993 3
1968 2
1977 2
1985 2
1992 2
1973 1
1994 1
1975 1
*/

-- Exercise 8
SELECT * FROM(
                 SELECT (EXTRACT(YEAR FROM ZATRUDNIONY)) AS ROK, COUNT(*) AS LICZBA FROM PRACOWNICY
                 GROUP BY (EXTRACT(YEAR FROM ZATRUDNIONY)))
WHERE LICZBA = (SELECT MAX(COUNT(*)) FROM PRACOWNICY
                GROUP BY (EXTRACT(YEAR FROM ZATRUDNIONY)));

/*
ROK LICZBA
---- ---------
1993 3
*/

-- Exercise 9
-- a)
SELECT NAZWISKO, PLACA_POD,
       (
           SELECT p.PLACA_POD - AVG(PLACA_POD) FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP=p.ID_ZESP
       )
           AS ROZNICA
FROM PRACOWNICY p
ORDER BY NAZWISKO;

-- b)
SELECT * FROM
    (SELECT NAZWISKO, PLACA_POD,
            (
                SELECT p.PLACA_POD - AVG(PLACA_POD)
                FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP=p.ID_ZESP
            )
                AS ROZNICA
     FROM PRACOWNICY p)
ORDER BY NAZWISKO;

/*
NAZWISKO PLACA_POD ROZNICA
--------------- --------- ---------
BIALY 250 -252
BLAZEWICZ 1350 0
BRZEZINSKI 960 343,4
HAPKE 480 -22
JEZIERSKI 439,7 -176,9
KONOPKA 480 -136,6
KOSZLAJDA 590 -26,6
KROLIKOWSKI 645,5 28,9
MAREK 410,2 -659,9
MATYSIAK 371 -245,6
MORZY 830 213,4
SLOWINSKI 1070 568
WEGLARZ 1730 659,9
ZAKRZEWICZ 208 -294
*/

-- Exercise 10
-- a)
SELECT NAZWISKO, PLACA_POD,
       (
           SELECT p.PLACA_POD - AVG(PLACA_POD)
           FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP=p.ID_ZESP
       )
           AS ROZNICA
FROM PRACOWNICY p
WHERE (SELECT p.PLACA_POD - AVG(PLACA_POD)
       FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP=p.ID_ZESP) > 0
ORDER BY NAZWISKO;

-- b)
SELECT * FROM
    (SELECT NAZWISKO, PLACA_POD,
            (
                SELECT p.PLACA_POD - AVG(PLACA_POD)
                FROM PRACOWNICY GROUP BY ID_ZESP HAVING ID_ZESP=p.ID_ZESP
            )
                AS ROZNICA
     FROM PRACOWNICY p)
WHERE ROZNICA > 0
ORDER BY NAZWISKO;

/*
NAZWISKO PLACA_POD ROZNICA
--------------- ----------- -------
BRZEZINSKI 960 343,4
KROLIKOWSKI 645,5 28,9
MORZY 830 213,4
SLOWINSKI 1070 568
WEGLARZ 1730 659,9
*/

-- Exercise 11
SELECT
    NAZWISKO,
    (SELECT COUNT(*) FROM PRACOWNICY p
                              INNER JOIN PRACOWNICY s ON p.ID_SZEFA = s.ID_PRAC
     GROUP BY s.NAZWISKO HAVING m.NAZWISKO = s.NAZWISKO)
        AS PODWLADNI
FROM
    PRACOWNICY m
WHERE
        ETAT = 'PROFESOR'
  AND
        ID_ZESP IN (10,20);

/*
NAZWISKO PODWLADNI
--------------- ---------
BRZEZINSKI 5
MORZY 2
*/

-- Exercise 12
SELECT
    NAZWA,
    SREDNIA_W_ZESPOLE,
    SREDNIA_OGOLNA,
    (CASE WHEN SREDNIA_W_ZESPOLE >= SREDNIA_OGOLNA THEN ':)'
          WHEN SREDNIA_W_ZESPOLE < SREDNIA_OGOLNA THEN ':('
          ELSE '???' END) AS NASTROJE
FROM
    (SELECT
         NAZWA,
         (SELECT AVG(p1.PLACA_POD)
          FROM PRACOWNICY p1
                   RIGHT JOIN ZESPOLY z1
                              ON p1.ID_ZESP = z1.ID_ZESP
          GROUP BY z1.NAZWA
          HAVING z.NAZWA = z1.NAZWA)
             AS SREDNIA_W_ZESPOLE,
         (SELECT AVG(PLACA_POD) FROM PRACOWNICY)
             AS SREDNIA_OGOLNA
     FROM
         ZESPOLY z)
ORDER BY NAZWA;

/*
NAZWA SREDNIA_W_ZESPOLE SREDNIA_OGOLNA NASTROJE
----------------------- ----------------- ---------------- --------
ADMINISTRACJA 1070,1 701,03 :)
ALGORYTMY 1350 701,03 :)
BADANIA OPERACYJNE 701,03 ???
SYSTEMY EKSPERCKIE 502 701,03 :(
SYSTEMY ROZPROSZONE 616,6 701,03 :(
*/

-- Exercise 13
SELECT
    *
FROM
    ETATY e
ORDER BY(
            SELECT COUNT(*)
            FROM PRACOWNICY
            GROUP BY ETAT
            HAVING ETAT = e.NAZWA)DESC,
        NAZWA;

/*
NAZWA PLACA_MIN PLACA_MAX
-------------- --------- -----------
ASYSTENT 300 500
PROFESOR 800 1500
ADIUNKT 510 750
STAZYSTA 150 250
DYREKTOR 1280 2100
SEKRETARKA 270 450
*/