-- Jezyk SQL. Rozdzial 9
-- DDL 2

-- Exercise 1
ALTER TABLE PROJEKTY ADD CONSTRAINT PK_PROJEKTY PRIMARY KEY (ID_PROJEKTU);
ALTER TABLE PROJEKTY ADD CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU);
ALTER TABLE PROJEKTY ADD CONSTRAINT OPIS_PROJEKTU NOT NULL;
ALTER TABLE PROJEKTY ADD CONSTRAINT DATA_ZAKONCZENIA
    CHECK (DATA_ZAKONCZENIA >= DATA_ROZPOCZECIA);
ALTER TABLE PROJEKTY ADD CONTRAINT FUNDUSZ
    CHECK (FUNDUSZ >= 0);

SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE AS C_TYPE,
    SEARCH_CONDITION,
    TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PROJEKTY';

/*
CONSTRAINT_NAME C_TYPE SEARCH_CONDITION COLUMN_NAME
--------------- ------ -------- -------------------------- --------------------
PK_PROJEKTY P ID_PROJEKTU
SYS_C0010038 C "ID_PROJEKTU" IS NOT NULL ID_PROJEKTU
SYS_C0010042 C data_zakonczenia > data_rozpoczecia DATA_ROZPOCZECIA
SYS_C0010042 C data_zakonczenia > data_rozpoczecia DATA_ZAKONCZENIA
SYS_C0010043 C fundusz > 0 FUNDUSZ
SYS_C0010044 C "OPIS_PROJEKTU" IS NOT NULL OPIS_PROJEKTU
UK_PROJEKTY U OPIS_PROJEKTU
*/

-- Exercise 2
INSERT INTO PROJEKTY
(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES
    ('Indeksy bitmapowe', to_date('12-05-2015','DD-MM-YYYY'),
     to_date('30-09-2016','DD-MM-YYYY'), 2016);

/*
Przyczyna bledu jest:
ORA-00001: naruszono wi?zy unikatowe (ZAO99548.UK_PROJEKTY)
*/

-- Exercise 3
CREATE TABLE PRZYDZIALY
(ID_PROJEKTU NUMBER(4,0),
 NR_PRACOWNIKA NUMBER(6,0),
 OD DATA DEFAULT SYSDATE,
 DO DATA,
 STAWKA NUMBER(7,2),
 ROLA VARCHAR2(20) CONSTRAINT CHK_PRZYDZIALY_ROLA
     CHECK (ROLA IN('KIERUJACY', 'ANALITYK', 'PROGRAMISTA')));
ALTER TABLE PRZYDZIALY ADD CONSTRAINT CHK_PRZYDZIALY_DATY CHECK (DO > OD);
ALTER TABLE PRZYDZIALY ADD CONSTRAINT PK_PRZYDZIALY PRIMARY KEY (ID_PROJEKTU, NR_PRACOWNIKA);
ALTER TABLE PRZYDZIALY ADD CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK (STAWKA > 0);
ALTER TABLE PRZYDZIALY ADD CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU);
ALTER TABLE PRZYDZIALY ADD CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC);

-- Exercise 4
INSERT INTO PRZYDZIALY (NR_PRACOWNIKA, OD, DO, STAWKA, ROLA)
VALUES (170, to_date('10-04-1999','DD-MM-YYYY'),
        to_date('10-05-1999','DD-MM-YYYY'), 1000, 'KIERUJACY');

INSERT INTO PRZYDZIALY (NR_PRACOWNIKA, OD, STAWKA, ROLA)
VALUES (140, to_date('01-12-2000','DD-MM-YYYY'),
        1500, 'ANALITYK');

INSERT INTO PRZYDZIALY (NR_PRACOWNIKA, OD, STAWKA, ROLA)
VALUES (140, to_date('14-09-20015','DD-MM-YYYY'),
        2500, 'KIERUJACY');

SELECT * FROM PRZYDZIALY;

/*
ID_PROJEKTU NR_PRACOWNIKA OD DO STAWKA ROLA
----------- ------------- ---------- ---------- ---------- --------------------
1 170 1999-04-10 1999-05-10 1000 KIERUJ?CY
1 140 2000-12-01 1500 ANALITYK
2 140 2015-09-14 2500 KIERUJ?CY
*/

-- Exercise 5
ALTER TABLE PRZYDZIALY ADD GODZINY INTEGER NOT NULL CHECK (GODZINY < 9999);

/*
Nie udalo sie dodac atrybutu.
*/

-- Exercise 6
ALTER TABLE PRZYDZIALY ADD GODZINY INTEGER;
UPDATE PRZYDZIALY SET GODZINY = 1;
ALTER TABLE PRZYDZIALY ADD CONSTRAINT CHK_GDOZINY CHECK (GODZINY < 9999);

-- Exercise 7
ALTER TABLE PROJEKTY DISABLE CONSTRAINT UK_PROJEKTY;

SELECT
    CONSTRAINT_NAME,
    STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PROJEKTY' AND CONSTRAINT_NAME = 'UK_PROJEKTY';

/*
CONSTRAINT_NAME STATUS
-------------------- --------
UK_PROJEKTY DISABLED
*/

-- Exercise 8
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe', to_date('12-04-2015','DD-MM-YYYY'),
        to_date('30-09-2016','DD-MM-YYYY'), 40000);

-- Powiodlo sie

SELECT * FROM PROJEKTY;
/*
ID_PROJEKTU OPIS_PROJEKTU DATA_ROZPOCZECIA DATA_ZAKONCZENIA FUNDUSZ
----------- ------------------ ---------------- ---------------- -------
1 Indeksy bitmapowe 1999-04-02 2001-08-31 25000
2 Sieci kr?gos?upowe 2017-02-21 19000
5 Indeksy bitmapowe 2015-04-12 2016-09-30 40000
*/

-- Exercise 9
ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;
/*
ORA-02299: nie mo?na zweryfikowa? poprawno?ci (ZAO99548.UK_PROJEKTY) - znaleziono zduplikowane klucze
*/

-- Exercise 10
UPDATE PROJEKTY SET OPIS_PROJEKTU = 'Inne indeksy' WHERE ID_PROJEKTU = 5;

ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;
/*
Table PROJEKTY altered.
*/

-- Exercise 11
ALTER TABLE PROJEKTY
    MODIFY OPIS_PROJEKTU VARCHAR(10);
/*
ORA-01441: nie mo?na zmniejszy? d?ugo?ci kolumny, poniewa? niektóre warto?ci s? zbyt du?e
*/

-- Exercise 12
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Sieci kregoslupowe';

-- Exercise 13
ALTER TABLE PRZYDZIALY DROP CONSTRAINT PK_PRZYDZIALY;

DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU = 'Sieci kregoslupowe';

SELECT * FROM PRZYDZIALY;
/*
ID_PROJEKTU OPIS_PROJEKTU DATA_ROZPOCZECIA DATA_ZAKONCZENIA FUNDUSZ
----------- ----------------- ---------------- ---------------- --------
1 Indeksy bitmapowe 1999-04-02 2001-08-31 25000
5 Inne indeksy 2015
*/
SELECT * FROM PROJEKTY;
/*
ID_PROJEKTU NR_PRACOWNIKA OD DO STAWKA ROLA GODZINY
----------- ------------- ---------- ---------- ------ --------- -------
1 170 1999-04-10 1999-05-10 1000 KIERUJ?CY 30
1 140 2000-12-01 1500 ANALITYK 30
*/

-- Exercise 14
DROP TABLE PROJEKTY PRIMARY KEY CASCADE;

SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE AS C_TYPE,
    SEARCH_CONDITION
FROM USER_CONSTRAINTS;

-- Exercise 15
DROP TABLE PRZYDZIALY;
DROP TABLE PROJEKTY_KOPIA;

SELECT table_name
FROM user_tables
ORDER BY table_name ASC;

/*
TABLE_NAME
----------------------
ETATY
PRACOWNICY
ZESPOLY
*/
